apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: model-api
  template:
    metadata:
      labels:
        app: model-api
    spec:
      containers:
      - name: model-api-container
        image: healthcare-model-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
