apiVersion: v1
kind: Service
metadata:
  name: model-api-service
  labels:
    release: prometheus
    app: model-api
spec:
  selector:
    app: model-api
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
